spring:
  application:
    name: bff-service

  datasource:
    url: jdbc:mysql://localhost:3306/gwent?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem

server:
  port: 8080

# Configuración de servicios internos
gwent:
  services:
    bff:
      v1-version: "api/v1/auth"
      register: "/register"
      login: "/login"

    jugador:
      base-url: "http://localhost:8082"
    ingame:
      base-url: "http://localhost:8083"
    auth:
      name: "auth-service"
      v1-version: "/v1"
      base-url: "http://localhost:8081/auth"
      register: "/register"
      login: "/login"


logging:
  level:
    org.springframework.security: DEBUG
